# Generated by Django 4.2 on 2024-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariostrime',
            name='Cedula_Usuario',
            field=models.CharField(max_length=18, unique=True, verbose_name='CEDULA'),
        ),
    ]
