# Generated by Django 4.2 on 2024-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usuariostrime_cedula_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariostrime",
            name="Departamento_Usuario",
            field=models.CharField(
                max_length=60, null=True, verbose_name="Departamento_Usuario"
            ),
        ),
    ]
