# Generated by Django 4.2 on 2024-10-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPDFS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('image', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
