# Generated by Django 4.2 on 2024-10-31 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FPDFS', '0004_pdfenviadosgerente_estatus_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondecompras',
            name='requisicionCancelada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FPDFS.pdfenviadoscompras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfenviadosalmacen',
            name='documento_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPDFS.pdfenviadosgerente'),
        ),
        migrations.AlterField(
            model_name='pdfenviadoscompras',
            name='documento_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPDFS.pdfenviadosalmacen'),
        ),
    ]
