# Generated by Django 4.2 on 2024-10-31 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FPDFS", "0005_cotizaciondecompras_requisicioncancelada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf2enviadoggeneral",
            name="cotizacionAcecptada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="FPDFS.cotizaciondecompras",
            ),
            preserve_default=False,
        ),
    ]
