# Generated by Django 4.2 on 2024-11-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FPDFS", "0010_alter_cotizaciondecompras_estatus_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfenviadosgerente",
            name="N_documento",
            field=models.CharField(
                max_length=22, null=True, verbose_name="Numero del documento"
            ),
        ),
        migrations.AddField(
            model_name="pdfenviadosgerente",
            name="descripcion_documento",
            field=models.CharField(blank=True, max_length=460, null=True),
        ),
        migrations.AddField(
            model_name="pdfenviadosgerente",
            name="nombre_documento",
            field=models.CharField(
                max_length=22, null=True, verbose_name="Nombre del documento"
            ),
        ),
    ]
