# Generated by Django 4.2 on 2024-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FPDFS", "0011_pdfenviadosgerente_n_documento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdfenviadosalmacen",
            options={
                "verbose_name": "Requisiciones Departamento de Almacen",
                "verbose_name_plural": "PDFtoAlmacen",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfenviadoscompras",
            options={"verbose_name": "Requisiciones Departamento de Compras"},
        ),
        migrations.AlterModelOptions(
            name="pdfenviadosgerente",
            options={
                "verbose_name": "Requisiciones a los Gerentes",
                "verbose_name_plural": "PDFtoGerente",
            },
        ),
        migrations.AddField(
            model_name="pdf2enviadoggeneral",
            name="N_documento",
            field=models.CharField(
                max_length=22, null=True, verbose_name="Numero del documento"
            ),
        ),
        migrations.AddField(
            model_name="pdf2enviadoggeneral",
            name="descripcion_documento",
            field=models.CharField(
                blank=True,
                max_length=460,
                null=True,
                verbose_name="Descripción del documento",
            ),
        ),
        migrations.AddField(
            model_name="solicitudordendecompras",
            name="N_documento",
            field=models.CharField(
                max_length=22, null=True, verbose_name="Numero del documento"
            ),
        ),
        migrations.AddField(
            model_name="solicitudordendecompras",
            name="descripcion_documento",
            field=models.CharField(
                blank=True,
                max_length=460,
                null=True,
                verbose_name="Descripción del documento",
            ),
        ),
        migrations.AlterField(
            model_name="pdfenviadosgerente",
            name="descripcion_documento",
            field=models.CharField(
                blank=True,
                max_length=460,
                null=True,
                verbose_name="Descripción del documento",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudordendecompras",
            name="nombre_documento",
            field=models.CharField(
                max_length=22, null=True, verbose_name="Nombre del documento"
            ),
        ),
    ]
