# Generated by Django 4.2 on 2025-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FPDFS", "0015_alter_pdfenviadosgerente_n_documento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizaciondecompras",
            name="nombre_documento",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pdf2enviadoggeneral",
            name="nombre_documento",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nombre del documento"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudordendecompras",
            name="nombre_documento",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nombre del documento"
            ),
        ),
    ]
